import {useCallback,useEffect,useId,useMemo,useRef,useState} from 'react';
import {Button,Glass,IconButton} from 'open-glass-ui';
import {ArrowDownToLine,Trash2,Copy,Focus,Frame,GitBranch,Grid2X2,Minus,MousePointer2,Plus,Redo2,Search,Undo2,Waypoints,Link2} from 'lucide-react';
import type {AgentPlan} from './types';
import {allEdges,clonePlan,defaultLayout,deleteWorker,disconnectLink,hiddenLink,isStage,linkKey,linksAt,MAX_NODES,NODE_H,NODE_W,reconnectLink,remapDuplicate,sideAllows,snapped,stagePoint,STAGE_IDS,type EndpointSide,type StageId} from './graph-model';
import './Graph.css';
type Props={plan:AgentPlan;onChange:(plan:AgentPlan)=>void;selectedId:string;onSelect:(id:string)=>void;locked:boolean;snap:boolean;onHint:(message:string)=>void;nodeStates:Record<string,string>;solo:boolean};
type Point={x:number;y:number};
type Edge={from:string;to:string};
type Gesture={kind:'move';ids:string[];start:Point;positions:Map<string,Point>;base:AgentPlan}|{kind:'pan';start:Point;camera:Point}|{kind:'wire';from:string;side:EndpointSide;attached?:Edge;start:Point;current:Point}|{kind:'cut';start:Point;current:Point}|null;
const stages:Record<StageId,string>={$input:'Input',$review:'Review',$output:'Output'};
const id=()=>`agent-${crypto.randomUUID().slice(0,8)}`;
const roleColor:Record<string,string>={supervisor:'violet',investigator:'teal',implementer:'teal',verifier:'teal'};

export default function Graph({plan,onChange,selectedId,onSelect,locked,snap,onHint,nodeStates,solo}:Props){
 const graphId=useId().replace(/:/g,'');
 const root=useRef<HTMLDivElement>(null),gesture=useRef<Gesture>(null),space=useRef(false),history=useRef<AgentPlan[]>([]),future=useRef<AgentPlan[]>([]),pendingOwn=useRef(''),priorPlan=useRef<AgentPlan|null>(null),fitRef=useRef<(min?:number)=>void>(()=>{}),initialFit=useRef(false),panMoved=useRef(false);
 const [camera,setCamera]=useState({x:0,y:0,z:1}),[preview,setPreview]=useState<AgentPlan|null>(null),[draft,setDraft]=useState<Point|null>(null),[multi,setMulti]=useState<string[]>([]),[selectedEdge,setSelectedEdge]=useState<Edge|null>(null),[menu,setMenu]=useState<Point|null>(null),[query,setQuery]=useState(''),[search,setSearch]=useState(false),[more,setMore]=useState(false),[ambiguous,setAmbiguous]=useState<{from:string;side:EndpointSide;items:Edge[];start:Point}|null>(null);
 const planSignature=JSON.stringify(plan);
 const displayed=useMemo(()=>defaultLayout(preview??plan),[preview,planSignature]);
 const points=useMemo(()=>new Map<string,Point>([...STAGE_IDS.map(k=>[k,stagePoint(displayed,k)] as [string,Point]),...displayed.Nodes.map(n=>[n.Id,{x:n.X,y:n.Y}] as [string,Point])]),[displayed]);
 const edges=useMemo(()=>allEdges(displayed),[displayed]);
 const rootAgent=displayed.Nodes.find(n=>n.Id==='root');
 const visibleNodes=solo?(rootAgent?[rootAgent]:[]):displayed.Nodes;
 const visibleEdges=solo&&rootAgent?[{from:'$input',to:'root'},{from:'root',to:'$review'},{from:'$review',to:'$output'}].filter(e=>!hiddenLink(displayed,e.from,e.to)):edges;
 const toWorld=useCallback((x:number,y:number)=>{const r=root.current!.getBoundingClientRect();return{x:(x-r.left-camera.x)/camera.z,y:(y-r.top-camera.y)/camera.z}},[camera]);
 const commit=useCallback((next:AgentPlan,base=displayed)=>{if(locked)return;history.current.push(clonePlan(base));if(history.current.length>60)history.current.shift();future.current=[];const safe=clonePlan(next);pendingOwn.current=JSON.stringify(safe);setPreview(null);onChange(safe)},[displayed,locked,onChange]);
 useEffect(()=>{if(!priorPlan.current){priorPlan.current=clonePlan(plan);return;}if(pendingOwn.current===planSignature){pendingOwn.current='';priorPlan.current=clonePlan(plan);return;}history.current.push(clonePlan(priorPlan.current));if(history.current.length>60)history.current.shift();future.current=[];priorPlan.current=clonePlan(plan);setPreview(null);},[planSignature]);
 const fit=useCallback((atLeast=.1)=>{if(!root.current)return;const boxes=[...points].map(([key,p])=>({x:p.x,y:p.y,w:isStage(key)?150:NODE_W,h:isStage(key)?64:NODE_H}));if(!boxes.length)return;const x=Math.min(...boxes.map(b=>b.x)),y=Math.min(...boxes.map(b=>b.y)),right=Math.max(...boxes.map(b=>b.x+b.w)),bottom=Math.max(...boxes.map(b=>b.y+b.h)),r=root.current.getBoundingClientRect(),z=Math.max(atLeast,Math.min(1,(r.width-100)/(right-x+80),(r.height-96)/(bottom-y+100))),centerX=(r.width-(x+right)*z)/2,centerY=(r.height-(y+bottom)*z)/2,tx=Math.max(24-x*z,centerX),ty=Math.max(80-y*z,centerY);setCamera({z,x:tx,y:Math.max(80-y*z,Math.min(ty,r.height-16-bottom*z))})},[points]);
 fitRef.current=fit;
 useEffect(()=>{if(!initialFit.current&&root.current){initialFit.current=true;requestAnimationFrame(()=>fitRef.current(.1));}const ro=new ResizeObserver(()=>{setMenu(null);setMore(false);if(initialFit.current&&!gesture.current)fitRef.current(.1)});if(root.current)ro.observe(root.current);return()=>ro.disconnect()},[]);
 const undo=(redo=false)=>{if(locked)return;const from=redo?future.current:history.current,to=redo?history.current:future.current,p=from.pop();if(p){to.push(clonePlan(displayed));pendingOwn.current=JSON.stringify(p);onChange(clonePlan(p));setPreview(null)}};
 const remove=(edge:Edge)=>commit(disconnectLink(displayed,edge.from,edge.to));
 const startWire=(e:React.PointerEvent,endpoint:string,side:EndpointSide)=>{if(space.current)return;if(locked||e.button!==0)return;e.preventDefault();e.stopPropagation();e.nativeEvent.stopImmediatePropagation?.();setMenu(null);setMore(false);setSearch(false);setSelectedEdge(null);const w=toWorld(e.clientX,e.clientY);let links=e.shiftKey?[]:linksAt(displayed,endpoint,side);if(selectedEdge&&links.some(edge=>edge.from===selectedEdge.from&&edge.to===selectedEdge.to))links=[selectedEdge];if(links.length>1){setAmbiguous({from:endpoint,side,items:links,start:w});return;}const attached=links[0];gesture.current={kind:'wire',from:endpoint,side,attached,start:w,current:w};setDraft(w);(e.currentTarget as HTMLElement).setPointerCapture(e.pointerId);root.current?.focus()};
 const move=(e:React.PointerEvent)=>{const g=gesture.current;if(!g)return;if(g.kind==='pan'){if(Math.abs(e.clientX-g.start.x)+Math.abs(e.clientY-g.start.y)>3)panMoved.current=true;setCamera(c=>({...c,x:g.camera.x+e.clientX-g.start.x,y:g.camera.y+e.clientY-g.start.y}));return;}const w=toWorld(e.clientX,e.clientY);if(g.kind==='wire'||g.kind==='cut'){gesture.current={...g,current:w};setDraft(w);return;}const dx=w.x-g.start.x,dy=w.y-g.start.y,p=clonePlan(g.base);for(const key of g.ids){const origin=g.positions.get(key)!;const x=snapped(origin.x+dx,snap),y=snapped(origin.y+dy,snap);if(isStage(key)){const s=p.Stages.find(s=>s.Id===key);if(s){s.X=x;s.Y=y}}else{const n=p.Nodes.find(n=>n.Id===key);if(n){n.X=x;n.Y=y}}}setPreview(p)};
 const finishWire=(g:Extract<Gesture,{kind:'wire'}>,e:React.PointerEvent)=>{setDraft(null);const el=document.elementFromPoint(e.clientX,e.clientY)?.closest<HTMLElement>('[data-endpoint][data-side]');const endpoint=el?.dataset.endpoint,side=el?.dataset.side as EndpointSide|undefined;if(!endpoint){if(g.attached)remove(g.attached);return;}let source:string,target:string,sourceSide:EndpointSide|undefined,targetSide:EndpointSide|undefined;if(g.attached){if(g.side==='out'){source=endpoint;target=g.attached.to;sourceSide=side;targetSide='in';}else{source=g.attached.from;target=endpoint;sourceSide='out';targetSide=side;}}else{const fromIsSource=sideAllows(g.from,g.side,'source');source=fromIsSource?g.from:endpoint;target=fromIsSource?endpoint:g.from;sourceSide=fromIsSource?g.side:side;targetSide=fromIsSource?side:g.side;}if(!sourceSide||!targetSide||!sideAllows(source,sourceSide,'source')||!sideAllows(target,targetSide,'target')){onHint('Use an output socket to start and an input socket to finish the connection.');return;}const result=reconnectLink(displayed,source,target,g.attached,sourceSide,targetSide);if(!result.plan){onHint(result.reason??'That connection is invalid.');return;}commit(result.plan);setSelectedEdge(null)};
 const finish=(e:React.PointerEvent)=>{const g=gesture.current;if(!g)return;gesture.current=null;if(g.kind==='pan'&&!panMoved.current){setMulti([]);setSelectedEdge(null);onSelect('');return;}if(g.kind==='move'&&preview){const moved=JSON.stringify(g.base)!==JSON.stringify(preview);if(moved){history.current.push(g.base);future.current=[];const safe=clonePlan(preview);pendingOwn.current=JSON.stringify(safe);priorPlan.current=clonePlan(safe);onChange(safe)}setPreview(null)}else if(g.kind==='wire')finishWire(g,e);else if(g.kind==='cut'){setDraft(null);const distance=(p:Point,a:Point,b:Point)=>{const dx=b.x-a.x,dy=b.y-a.y,t=Math.max(0,Math.min(1,((p.x-a.x)*dx+(p.y-a.y)*dy)/(dx*dx+dy*dy||1)));return Math.hypot(p.x-a.x-t*dx,p.y-a.y-t*dy)};const hit=visibleEdges.filter(edge=>{for(let i=0;i<=32;i++)if(distance(curve(edge,i/32),g.start,g.current)<12)return true;return false});if(hit.length){let p=clonePlan(displayed);hit.forEach(e=>{p=disconnectLink(p,e.from,e.to)});commit(p);setSelectedEdge(null)}}};
 const cancel=()=>{gesture.current=null;setDraft(null);setPreview(null);setAmbiguous(null)};
 const down=(e:React.PointerEvent<HTMLDivElement>)=>{const el=e.target as HTMLElement;if(!el.closest('.laica-context,.laica-graph-toolbar,.laica-search')){setMenu(null);setMore(false);setSearch(false);setAmbiguous(null)}if(e.button===2&&e.ctrlKey){e.preventDefault();const w=toWorld(e.clientX,e.clientY);gesture.current={kind:'cut',start:w,current:w};setDraft(w);e.currentTarget.setPointerCapture(e.pointerId);return;}const onBackground=!el.closest('.laica-node,.laica-stage,.laica-context,.laica-graph-toolbar,.laica-search,.laica-tools-pop,.laica-edge-hit');if(e.button===1||e.button===0&&(space.current||onBackground)){e.preventDefault();panMoved.current=false;gesture.current={kind:'pan',start:{x:e.clientX,y:e.clientY},camera:{x:camera.x,y:camera.y}};e.currentTarget.setPointerCapture(e.pointerId);root.current?.focus()}};
 const dragItem=(e:React.PointerEvent,id:string)=>{if(e.button!==0||locked||space.current)return;e.stopPropagation();root.current?.focus();setMenu(null);setMore(false);setSearch(false);setAmbiguous(null);setSelectedEdge(null);const w=toWorld(e.clientX,e.clientY);if(e.shiftKey){setMulti(v=>v.includes(id)?v.filter(k=>k!==id):[...v,id]);onSelect(id);return;}if(!multi.includes(id))setMulti([id]);onSelect(id);const ids=multi.includes(id)?multi:[id];gesture.current={kind:'move',ids,start:w,positions:new Map(ids.map(k=>[k,points.get(k)!])),base:clonePlan(displayed)};(e.currentTarget as HTMLElement).setPointerCapture(e.pointerId)};
 const add=()=>{if(locked||displayed.Nodes.length>=MAX_NODES){onHint('The graph can contain up to 100 workers.');return;}const p=clonePlan(displayed),rootNode=p.Nodes.find(n=>n.Id==='root');if(!rootNode){onHint('The plan root is unavailable.');return;}const world=root.current?toWorld(root.current.getBoundingClientRect().left+root.current.clientWidth/2,root.current.getBoundingClientRect().top+root.current.clientHeight/2):{x:540,y:220};p.Nodes.push({Id:id(),ParentId:'root',Name:'New worker',Role:'implementer',Model:(rootNode.ConnectionId||'codex')==='codex'?'gpt-6-luna':rootNode.Model,Effort:(rootNode.ConnectionId||'codex')==='codex'?'medium':'default',Job:'Describe the work for this agent.',ConnectionId:rootNode.ConnectionId||'codex',X:world.x,Y:world.y});commit(p);onSelect(p.Nodes.at(-1)!.Id)};
 const duplicate=()=>{if(locked)return;const selected=multi.length?multi:[selectedId].filter(Boolean),p=remapDuplicate(displayed,selected,id);if(p.Nodes.length===displayed.Nodes.length){onHint('Select workers to duplicate; the graph limit is 100.');return;}commit(p)};
 const arrange=()=>{const p=clonePlan(displayed),rootNode=p.Nodes.find(n=>n.Id==='root');if(!rootNode){onHint('The plan root is unavailable.');return;}const depth=new Map<string,number>([['root',0]]);for(const n of p.Nodes)if(n.Id!=='root'&&!n.ParentId)depth.set(n.Id,1);let changed=true;while(changed){changed=false;for(const n of p.Nodes)if(n.ParentId&&depth.has(n.ParentId)&&!depth.has(n.Id)){depth.set(n.Id,depth.get(n.ParentId)!+1);changed=true;}}for(const n of p.Nodes)if(!depth.has(n.Id))depth.set(n.Id,1);const slots=new Map<number,number>();rootNode.X=270;rootNode.Y=220;let maxDepth=0;for(const n of p.Nodes){if(n.Id==='root')continue;const d=depth.get(n.Id)??1,slot=slots.get(d)??0;slots.set(d,slot+1);maxDepth=Math.max(maxDepth,d);n.X=270+d*250;n.Y=40+slot*150;}const stageX=(id:string)=>id==='$input'?rootNode.X-260:id==='$review'?rootNode.X+250*(maxDepth+1):rootNode.X+250*(maxDepth+1)+230;for(const s of p.Stages??[]){s.X=stageX(s.Id);s.Y=220;}commit(p);requestAnimationFrame(()=>fitRef.current(.1))};
 const frameSelection=()=>{const selected=multi.length?multi:[selectedId],items=selected.flatMap(key=>{const p=points.get(key);return p?[{x:p.x,y:p.y,w:isStage(key)?150:NODE_W,h:isStage(key)?64:NODE_H}]:[]});if(!items.length||!root.current)return;const x=Math.min(...items.map(p=>p.x)),y=Math.min(...items.map(p=>p.y)),right=Math.max(...items.map(p=>p.x+p.w)),bottom=Math.max(...items.map(p=>p.y+p.h)),r=root.current.getBoundingClientRect(),z=Math.max(.8,Math.min(1.2,(r.width-120)/(right-x+60),(r.height-140)/(bottom-y+80)));setCamera({z,x:(r.width-(x+right)*z)/2,y:(r.height-(y+bottom)*z)/2+48})};
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){cancel();setMenu(null);setMore(false);setSearch(false);setAmbiguous(null);return;}const active=document.activeElement as HTMLElement|null;if(/INPUT|TEXTAREA|SELECT/.test(active?.tagName??'')||active?.isContentEditable||document.querySelector('[role=dialog],.gs-pop'))return;if(!root.current)return;if(e.code==='Space'){e.preventDefault();space.current=true}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();undo(e.shiftKey)}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();undo(true)}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='a'){e.preventDefault();setMulti(displayed.Nodes.map(n=>n.Id));onHint(displayed.Nodes.length+' worker'+(displayed.Nodes.length===1?'':'s')+' selected.');}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='d'){e.preventDefault();duplicate();}if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();deleteSelection();}};const up=(e:KeyboardEvent)=>{if(e.code==='Space')space.current=false};const blur=()=>{space.current=false};const outside=(e:PointerEvent)=>{if(!root.current?.contains(e.target as Node)){setMenu(null);setMore(false);setSearch(false);setAmbiguous(null)}};window.addEventListener('keydown',key);window.addEventListener('keyup',up);window.addEventListener('blur',blur);document.addEventListener('pointerdown',outside);return()=>{window.removeEventListener('keydown',key);window.removeEventListener('keyup',up);window.removeEventListener('blur',blur);document.removeEventListener('pointerdown',outside)}},[displayed,locked,selectedEdge,selectedId,multi]);
 const curve=(edge:Edge,t:number):Point=>{const a=points.get(edge.from),b=points.get(edge.to);if(!a||!b)return{x:0,y:0};const sx=a.x+(isStage(edge.from)?150:NODE_W),sy=a.y+(isStage(edge.from)?32:NODE_H/2),ex=b.x,ey=b.y+(isStage(edge.to)?32:NODE_H/2),dx=Math.max(50,Math.abs(ex-sx)*.48),u=1-t;return{x:u*u*u*sx+3*u*u*t*(sx+dx)+3*u*t*t*(ex-dx)+t*t*t*ex,y:u*u*u*sy+3*u*u*t*sy+3*u*t*t*ey+t*t*t*ey}};
 const path=(edge:Edge)=>{const a=points.get(edge.from),b=points.get(edge.to);if(!a||!b)return '';const sx=a.x+(isStage(edge.from)?150:NODE_W),sy=a.y+(isStage(edge.from)?32:NODE_H/2),ex=b.x,ey=b.y+(isStage(edge.to)?32:NODE_H/2),dx=Math.max(50,Math.abs(ex-sx)*.48);return `M ${sx} ${sy} C ${sx+dx} ${sy}, ${ex-dx} ${ey}, ${ex} ${ey}`};
 const deleteSelection=()=>{if(locked){onHint('Stop the running team before editing the graph.');return;}if(selectedEdge){remove(selectedEdge);setSelectedEdge(null);onHint('Connection removed.');return;}const wanted=(multi.length?multi:[selectedId]).filter(Boolean);if(!wanted.length){onHint('Select a worker or a connection first, then press Delete.');return;}if(wanted.every(isStage)){onHint("Input, Review and Output are fixed stages and can't be deleted. You can move them or disconnect their links.");return;}let p=clonePlan(displayed),removed=0,skippedRoot=false;for(const key of wanted){if(isStage(key))continue;if(key==='root'){skippedRoot=true;continue;}const before=p.Nodes.length;p=deleteWorker(p,key);if(p.Nodes.length<before)removed++;}if(removed){commit(p);setMulti([]);onSelect('root');onHint('Deleted '+removed+' worker'+(removed===1?'':'s')+(skippedRoot?'. The supervisor stays because every team needs one.':'.'));}else if(skippedRoot)onHint("The supervisor can't be deleted because every team needs one. Select a worker instead, or start a New team.");};
 const selectRelated=()=>{const related=displayed.Nodes.filter(n=>n.ParentId===selectedId||displayed.Nodes.find(x=>x.Id===selectedId)?.ParentId===n.Id).map(n=>n.Id);setMulti(related);onHint(`${related.length} linked worker${related.length===1?'':'s'} selected.`)};
 return <div ref={root} className="laica-graph" tabIndex={0} onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node|null))space.current=false}} onPointerDown={down} onPointerMove={move} onPointerUp={finish} onPointerCancel={cancel} onLostPointerCapture={()=>{if(gesture.current)cancel()}} onContextMenu={e=>{e.preventDefault();if(e.ctrlKey)return;const hitNode=(e.target as HTMLElement).closest<HTMLElement>('[data-endpoint]:not(.laica-socket)');const hitId=hitNode?.dataset.endpoint;if(hitId){if(!multi.includes(hitId))setMulti([hitId]);onSelect(hitId);setSelectedEdge(null);}const r=root.current!.getBoundingClientRect();setMenu({x:Math.max(8,Math.min(e.clientX-r.left,r.width-212)),y:Math.max(8,Math.min(e.clientY-r.top,r.height-348))});setQuery('')}} onWheel={e=>{if((e.target as HTMLElement).closest('.laica-context,.laica-tools-pop,.laica-search'))return;e.preventDefault();const r=root.current!.getBoundingClientRect(),wx=(e.clientX-r.left-camera.x)/camera.z,wy=(e.clientY-r.top-camera.y)/camera.z,z=Math.max(.1,Math.min(1.5,camera.z*(e.deltaY<0?1.1:.9)));setCamera({z,x:e.clientX-r.left-wx*z,y:e.clientY-r.top-wy*z})}}>
  <div className="laica-graph-camera" style={{left:camera.x,top:camera.y}}><div className="laica-graph-world" style={{zoom:camera.z}}><svg className="laica-graph-edges" width="1" height="1" aria-label="Plan connections"><defs><marker id={`${graphId}-arrow`} markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0 0L8 4L0 8" fill="none" stroke="currentColor"/></marker></defs>{visibleEdges.map(edge=><g key={linkKey(edge.from,edge.to)}><path className={`laica-edge ${selectedEdge?.from===edge.from&&selectedEdge.to===edge.to?'is-selected':''}`} d={path(edge)} markerEnd={`url(#${graphId}-arrow)`}/><path className="laica-edge-hit" d={path(edge)} onClick={e=>{e.stopPropagation();setSelectedEdge(edge);onSelect(edge.to);root.current?.focus()}} aria-label={`Connection ${edge.from} to ${edge.to}`}/></g>)}{draft&&gesture.current?.kind==='cut'&&<path className="laica-cut-preview" d={`M${gesture.current.start.x} ${gesture.current.start.y}L${draft.x} ${draft.y}`}/ >}{draft&&gesture.current?.kind==='wire'&&<path className="laica-edge is-draft" d={`M${gesture.current.start.x} ${gesture.current.start.y}L${draft.x} ${draft.y}`}/>}</svg>
   {STAGE_IDS.map(stage=>{const p=points.get(stage)!;return <Glass key={stage} material="frosted" className={`laica-stage ${selectedId===stage?'is-selected':''}`} style={{left:p.x,top:p.y}} role="group" tabIndex={0} aria-label={`${stages[stage]} stage`} data-endpoint={stage} onPointerDown={e=>dragItem(e,stage)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setSelectedEdge(null);onSelect(stage)}}} onClick={()=>{setSelectedEdge(null);onSelect(stage)}}><span className="laica-stage-kicker">STAGE</span><strong>{stages[stage]}</strong>{stage!=='$output'&&<Button className="laica-socket stage-socket" data-endpoint={stage} data-side="out" aria-label={`${stages[stage]} output socket`} onPointerDown={e=>startWire(e,stage,'out')} onClick={e=>e.stopPropagation()}/ >}{stage!=='$input'&&<Button className="laica-socket stage-socket-in" data-endpoint={stage} data-side="in" aria-label={`${stages[stage]} input socket`} onPointerDown={e=>startWire(e,stage,'in')} onClick={e=>e.stopPropagation()}/>}</Glass>})}
   {visibleNodes.map(n=><Glass key={n.Id} material="regular" className={`laica-node ${selectedId===n.Id?'is-selected':''} ${multi.includes(n.Id)?'is-multi':''}`} style={{left:n.X,top:n.Y}} data-endpoint={n.Id} role="group" tabIndex={0} aria-label={`${n.Name}, ${n.Role}`} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onSelect(n.Id)}}} onPointerDown={e=>dragItem(e,n.Id)} onClick={()=>{setSelectedEdge(null);onSelect(n.Id)}}><Button className="laica-socket left" data-endpoint={n.Id} data-side="in" aria-label={`Input socket for ${n.Name}`} onPointerDown={e=>startWire(e,n.Id,'in')} onClick={e=>e.stopPropagation()}/><div className={`laica-role-dot ${roleColor[n.Role]??'teal'}`}/><div className="laica-node-copy"><span className="laica-node-role">{n.Role||'Worker'}</span><strong>{n.Name}</strong><span className="laica-node-meta">{n.Model} · {n.Effort}</span><span className="laica-node-job">{nodeStates[n.Id]||n.Job}</span></div><Button className="laica-socket right" data-endpoint={n.Id} data-side="out" aria-label={`Output socket for ${n.Name}`} onPointerDown={e=>startWire(e,n.Id,'out')} onClick={e=>e.stopPropagation()}/></Glass>)}
  </div></div>
  <div className="laica-graph-toolbar" role="toolbar" aria-label="Graph tools"><IconButton title="Add worker" aria-label="Add worker" onClick={add}><Plus/></IconButton><IconButton title="Delete selected (Del)" aria-label="Delete selected" onClick={deleteSelection}><Trash2/></IconButton><span className="laica-tool-divider"/><IconButton title="Zoom out" aria-label="Zoom out" onClick={()=>setCamera(c=>({...c,z:Math.max(.1,c.z-.1)}))}><Minus/></IconButton><span className="laica-zoom">{Math.round(camera.z*100)}%</span><IconButton title="Zoom in" aria-label="Zoom in" onClick={()=>setCamera(c=>({...c,z:Math.min(1.5,c.z+.1)}))}><Plus/></IconButton><IconButton title="Fit graph" aria-label="Fit graph" onClick={()=>fit()}><Focus/></IconButton><IconButton title="Undo" aria-label="Undo" onClick={()=>undo()}><Undo2/></IconButton><IconButton title="Redo" aria-label="Redo" onClick={()=>undo(true)}><Redo2/></IconButton><IconButton title="More graph tools" aria-label="More graph tools" onClick={()=>setMore(v=>!v)}><Waypoints/></IconButton>{more&&<Glass className="laica-tools-pop" material="frosted"><Button variant="quiet" size="small" onClick={()=>{setSearch(true);setMore(false)}}><Search/> Find node</Button><Button variant="quiet" size="small" onClick={duplicate}><Copy/> Duplicate selected</Button><Button variant="quiet" size="small" onClick={frameSelection}><Frame/> Frame selection</Button><Button variant="quiet" size="small" onClick={arrange}><GitBranch/> Arrange graph</Button><Button variant="quiet" size="small" onClick={deleteSelection}><Trash2/> Delete selected</Button><Button variant="quiet" size="small" onClick={selectRelated}><Link2/> Select linked workers</Button><span className="laica-grid-state"><Grid2X2/> Grid snapping {snap?'on':'off'}</span><Button variant="quiet" size="small" onClick={()=>{const p=clonePlan(displayed);p.HiddenStageLinks=[];commit(p)}}><ArrowDownToLine/> Restore stage links</Button></Glass>}</div>
  {ambiguous&&<Glass className="laica-context" material="frosted" style={{left:24,top:72}}><strong>Choose a connection</strong>{ambiguous.items.map(edge=><Button key={linkKey(edge.from,edge.to)} onClick={()=>{setSelectedEdge(edge);setAmbiguous(null);onHint(`Selected ${edge.from} → ${edge.to}. Pull a socket to reconnect or release empty space to disconnect.`)}}>{edge.from} → {edge.to}</Button>)}<Button onClick={()=>{setSelectedEdge(null);setAmbiguous(null);onHint('Hold Shift while pulling this socket to start a new connection.')}}>Start a new connection</Button></Glass>}
  {search&&<Glass className="laica-search" material="frosted"><Search/><input autoFocus placeholder="Find a worker" onKeyDown={e=>e.key==='Escape'&&setSearch(false)} onChange={e=>{const n=displayed.Nodes.find(n=>n.Name.toLowerCase().includes(e.target.value.toLowerCase()));if(n){onSelect(n.Id);setCamera(c=>({...c,x:root.current!.clientWidth/2-(n.X+NODE_W/2)*c.z,y:root.current!.clientHeight/2-(n.Y+NODE_H/2)*c.z}))}}}/><Button onClick={()=>setSearch(false)}>Close</Button></Glass>}
  {menu&&<div className="laica-context" role="menu" aria-label="Graph commands" style={{left:menu.x,top:menu.y}}><input autoFocus placeholder="Search commands" value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==='Escape'&&setMenu(null)}/>{[['Add worker',add],['Duplicate selected',duplicate],['Delete selected',deleteSelection],['Select all workers',()=>{setMulti(displayed.Nodes.map(n=>n.Id));onHint(displayed.Nodes.length+' workers selected.')}],['Arrange graph',arrange],['Frame selection',frameSelection],['Find worker',()=>setSearch(true)],['Select linked workers',selectRelated],['Restore stage links',()=>{const p=clonePlan(displayed);p.HiddenStageLinks=[];commit(p)}],['Disconnect selected',()=>{if(selectedEdge){remove(selectedEdge);setSelectedEdge(null);}else onHint('Click a connection line first, then choose Disconnect, or just press Delete.')}],['Undo',()=>undo()],['Redo',()=>undo(true)]].filter(([label])=>String(label).toLowerCase().includes(query.toLowerCase())).map(([label,fn])=><Button variant="quiet" size="small" key={String(label)} onClick={()=>{(fn as ()=>void)();setMenu(null)}}>{String(label)}</Button>)}</div>}
 </div>
}
